org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=26.1
loader_version=0.18.5
# Mod Properties
maven_group=com.skaggsm
archives_base_name=fabric-26.1-mumblelink-mod
modrinth_id=3QyVJtCB
# Dependencies
fabric_version=0.144.3+26.1
kotlin_version=1.13.10+kotlin.2.3.20
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
# Don't include the standard library, it's already bundled with fabric-language-kotlin
kotlin.stdlib.default.dependency=false
